### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by devramsean0** [UTCSheffield/SportsDay-Scoreboard#4]
We should authenticate all controllers except those required for auth.
- Microsoft OAUTH2 on our Microsoft tenancy
- Allowlist of emails for auth
- Use the session where possible

**Comment by northeastprince** [comment]
If there aren't going to be a ton of people logging in then I would avoid OAuth and just have an interface to add users by email.

**Comment by devramsean0** [comment]
It's a lot of people annoyingly.
The plan is for everbody in the school to have some kind of permission level

**Comment by northeastprince** [comment]
A ton of people updating scores or just viewing them? If that latter, couldn't those pages be public?

**Comment by devramsean0** [comment]
I believe the intention is to restrict them to members of the school, Although I could consider making those pages unauthenticated.
As far as updating scores, An entire year group + staff members are going to have permissions (quite a few people lol)

**Comment by mr-eggleton** [comment]
The viewing can be public.

It doesn't need to be a lot of people who can edit, but as I had a MS Authentication proxy and a regex based authorisation system lying around on a server that I control thought we could use that and so there is less load on you.

I sent you sample code about that (and have now fixed the server) but the sample code also extracts info from the JWT and you don't need that you just need to know if the authenticated user has the "scorer" role by calling the roles endpoint

But Matt's suggestion is also completely fine for the small thing we are doing.
________________________________

**Comment by devramsean0** [comment]
I eventually decided on using the microsoft oauth proxy. because it's less code + allows for this service to be deployed in years to come without having to have extreme knowledge of what is happening with it.
I'm also leaving the scoreboard page itself unauthenticated
