### ISSUE TITLE
Public Analytics (Post event)

### ISSUE THREAD

**Issue by devramsean0** [UTCSheffield/SportsDay-Scoreboard#5]
Detailed information about each event,
publicly available

Send Summary Email??

**Comment by mr-eggleton** [comment]
Sending a summary might be a bit much but making a page is a decent idea.

**Comment by devramsean0** [comment]
Yeah, that's fair

**Comment by mr-eggleton** [comment]
Is this the same as the results page #8 ?

**Comment by devramsean0** [comment]
I do believe so!
